- url: https://www.meckeys.com/shop/keyboard/80-keyboard/keychron-k8-pro/
  source: '#product-28552 > span'
  message: Out of Stock
  is_xpath: false
  tags: [ 'keyboard' ]

- url: https://github.com/kislyuk/yq
  source: '#readme > div.Box-body.px-5.pb-5 > article > h2:nth-child(35)'
  message: Out of Stock
  is_xpath: false
  tags: [ 'github' ]